apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gymtonic-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /gymtonic
spec:
  rules:
    - http:
        paths:
          - path: /gymtonic
            pathType: Prefix
            backend:
              service:
                name: gymtonic
                port:
                  number: 8080
